version: '3.8'

services:
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: coffee_shop
      POSTGRES_USER: coffee_admin
      POSTGRES_PASSWORD: your_strong_password
    ports:
      - "5432:5432"
    volumes:
      - coffee_postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U coffee_admin -d coffee_shop"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    # volumes:
    #   - ./app:/app
    #   - /app/node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgresql://coffee_admin:your_strong_password@db:5432/coffee_shop
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - NODE_ENV=development
      - POSTGRES_PASSWORD=your_strong_password
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  coffee_postgres_data: 